### ISSUE TITLE
unable to run after build

### ISSUE THREAD

**Issue by ficapy** [antelle/wasm-image-compressor#1]
```
cmake version 3.10.0
```

```
emcc -v                                                                                                                                                                     
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.24
clang version 4.0.0  (emscripten 1.37.24 : 1.37.24)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /usr/local/opt/emscripten/libexec/llvm/bin
```
get image_compressor.js and image_compressor.wasm after the build of the document,but it's wrong to run in the browser.the browser console output information as follows

```
:8000/image_compressor.wasm:1 GET http://127.0.0.1:8000/image_compressor.wasm 404 (File not found)
worker.js:48 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': CompileError: AsyncCompile: Wasm decoding failed: expected magic word 00 61 73 6d, found 3c 68 65 61 @+0 could not be cloned.
    at Object.log [as print] (http://127.0.0.1:8000/worker.js:48:10)
    at abort (http://127.0.0.1:8000/dist/image_compressor.js:1:43635)
    at http://127.0.0.1:8000/dist/image_compressor.js:1:25934
    at <anonymous>
log @ worker.js:48
abort @ image_compressor.js:1
(anonymous) @ image_compressor.js:1
Promise.catch (async)
instantiateArrayBuffer @ image_compressor.js:1
doNativeWasm @ image_compressor.js:1
Module.asm @ image_compressor.js:1
(anonymous) @ image_compressor.js:1
(anonymous) @ worker.js:7
index.js:75 Uncaught TypeError: Cannot read property 'innerHTML' of undefined
    at log (index.js:75)
    at logError (index.js:79)
    at Worker.worker.onmessage.e (index.js:10)
```

p.s if use the original file directly,everything is ok~

**Comment by antelle** [comment]
Probably you served it directly as is, it won't work, you should use `./serve.sh` instead.

**Comment by ficapy** [comment]
i know
```
git clone --recursive git@github.com:antelle/wasm-image-compressor.git
cd wasm-image-compressor
./build.sh

npm install http-server -g
./server.sh
```
but it doesn't work, If ./build.sh is not executed, then it is normal

**Comment by antelle** [comment]
Probably something is wrong with your emscripten. It requests `/image_compressor.wasm` instead of `dist/image_compressor.wasm`. The url is defined [here](https://github.com/antelle/wasm-image-compressor/blob/master/docs/worker.js#L2) and em runtime must use from `Module` variable.

**Comment by ficapy** [comment]
problem solved.now it can run normally.the main reason is that the js difference generated by different versions of emcc.
under the new version,the wasmBinaryFile paramentes can not be overwritten.

```
  var wasmTextFile = 'image_compressor.wast';
  var wasmBinaryFile = 'image_compressor.wasm';
  var asmjsCodeFile = 'image_compressor.temp.asm.js';
```

```
    var wasmTextFile = Module["wasmTextFile"] || "image_compressor.wast";
    var wasmBinaryFile = Module["wasmBinaryFile"] || "image_compressor.wasm";
    var asmjsCodeFile = Module["asmjsCodeFile"] || "image_compressor.temp.asm.js";
```

as the same time,the new js file lacks `Module['getValue'] = getValue`

thanks for your help :)
